spring.application.name=SlotBooking

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=videoslots;encrypt=true;trustServerCertificate=true
spring.datasource.username=Bhanu
spring.datasource.password=Bhanu@09
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


spring.mail.username=bhanuprakashreddyyettapu@gmail.com
spring.mail.password=usfxoxevmlzqxiig
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true